### PR TITLE
Feat graalvm

### PR DESCRIPTION
**Pull request by xhanin**
Integrate GraalVM integration in build

### CODE REVIEW

**Comment by xhanin** [comment]
Not ready - we need to fix CircleCI integration

**Comment by xhanin** [comment]
The build is now passing on CircleCI, I think we can merge that to `dev`

**Review by driccio — APPROVED** [review]

**Comment by mrenou** [comment]
build passes on circleci

**Review by mrenou — APPROVED** [review]
build passes on circleci

**Pull request merged**
